[package]
name = "graphics"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
dynlib.workspace = true
log.workspace = true
raw-window-handle.workspace = true

[build-dependencies]
anyhow.workspace = true
gl-generator.workspace = true
