[package]
name = "app"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
raw-window-handle.workspace = true
# workspace
gl.workspace = true
window.workspace = true
