[package]
name = "w0"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
dynlib.workspace = true
log.workspace = true

[build-dependencies]
anyhow.workspace = true
wayland-scanner.workspace = true
